### ISSUE TITLE
Link to documentation in README.md is out of date

### ISSUE THREAD

**Issue by psmears** [messagebird/python-rest-api#14]
The README.md file says, at the end:

> Complete documentation, instructions, and examples are available at: https://www.messagebird.com/developers/python.

However, this link redirects to the generic https://developers.messagebird.com/ page, which is not Python-specific.

Either the link should be updated to point to Python-specific documentation, or it should point to the generic page (so that users aren't confused/frustrated at getting a generic page when they've been led to expect a Python-specific one).

**Comment by epels** [comment]
Hi @psmears, thanks for the heads up - the URLs have been fixed in #18.
