### ISSUE TITLE
add __str__ to returned message object for logging

### ISSUE THREAD

**Issue by yipcma** [messagebird/python-rest-api#16]

**Comment by epels** [comment]
Hi @yipcma, thank you for opening an issue!

I think creating string representations of the objects is best considered on a case-by-case basis by implementers. If we were to do this in the client itself, it would probably look something like this:

```python
def __str__(self):
    return self.__dict__.__str__()
```

This would however make it very appealing and easy to simply log that without much thought, but some objects - like messages - may, for some use-cases, contain very sensitive data (think: 2FA codes, password reset links...)
That is of course a pretty serious security issue. Not having a `__str__` implementation on these objects triggers people to think a bit more about what to log.

Hopefully you understand this concern, and thanks again for your suggestion!
