### ISSUE TITLE
Not able to send message from python file

### ISSUE THREAD

**Issue by maitri2705** [messagebird/python-rest-api#17]
I am following this process using messagebird library.
I am combining message_create.py and message.py.

client = messagebird.Client(ACCESS_KEY)
msg = client.message_create(originator_phonenumber, array of recipient_phonenumber, 'Hello World')
ms = client.message(msg.id)

and I am getting this error:
An error occured while requesting a Message object:
  code        : 20
  description : message not found
  parameter   : None

@samwierema Please help me on this.

**Comment by epels** [comment]
Hi @maitri2705, thanks for opening an issue!

Shortly after you posted I could reproduce this issue with both the Python client and another. Hence, I believe it took some time for the messages to become available for retrieval by their IDs in our API. After retrying just now, your code seems to work as expected though - can you please give it another go and let me know what happens?

Thanks!

**Comment by maitri2705** [comment]
Hi @epels ,
This issue has been resolved.
I was using testing key instead of live key of messagebird.
I initiated one live key to send message.

Thanks!
