### ISSUE TITLE
pip update

### ISSUE THREAD

**Issue by Pamzus** [messagebird/python-rest-api#49]
It seems like your pip version is not updated.
Calling >>>pip install messagebird installs package version 1.4.1. This is how messagebird/client.py looks like:

> class Client(object):
        def __init__(self, access_key, http_client=None):

This is version on git:

> class Client(object):
    def __init__(self, access_key, http_client=None, features=[]):

**Comment by dysosmus** [comment]
Hi, thank you for noticing it, we indeed forgot to release the version `1.5.0`. 
You can find the new release [here](https://github.com/messagebird/python-rest-api/releases/tag/1.5.0) on GitHub and [there](https://pypi.org/project/messagebird/1.5.0/) on PyPI.
