### ISSUE TITLE
Waiting for new release on pip

### ISSUE THREAD

**Issue by AbdurRehmanKhalil-arbisoft** [messagebird/python-rest-api#71]
I see that you have implemented `RequestValidator` but it's not released yet.

Since, I (and many others) add packages via pip, the latest version we have is v2.0.0. Using that version, I can't migrate request validation from `MessageBird-Signature and MessageBird-Request-Timestamp` to `MessageBird-Signature-JWT header`.

Thanks.

**Comment by juanbenitezdev** [comment]
Any news about this?

**Comment by nqkdev** [comment]
v2.1.0 is released. Sorry for the long wait. 🙏
